import hre from "hardhat";
import { parseEther } from "viem";

async function main() {
  console.log("🚀 Starting deployment of dfm contracts...\n");

  // 1. Get default wallet clients (accounts generated by Hardhat)
  const [deployer, seller, buyer] = await hre.viem.getWalletClients();
  const publicClient = await hre.viem.getPublicClient();

  // 2. Deploy Marketplace.sol
  console.log("Deploying Marketplace...");
  const marketplace = await hre.viem.deployContract("Marketplace");
  console.log(`✅ Marketplace deployed to: ${marketplace.address}`);

  // 3. Deploy Ratings.sol
  console.log("Deploying Ratings...");
  const ratings = await hre.viem.deployContract("Ratings");
  console.log(`✅ Ratings deployed to: ${ratings.address}`);

  // 4. Deploy Disputes.sol
  console.log("Deploying Disputes...");
  // Pass the deployer's address as the _admin argument for the constructor
  const disputes = await hre.viem.deployContract("Disputes", [deployer.account.address]); 
  console.log(`✅ Disputes deployed to: ${disputes.address}\n`);

  // 5. Setup initial test data (so your frontend isn't empty)
  console.log(`Creating an initial Gig using Seller account (${seller.account.address})...`);
  
  const createGigTx = await marketplace.write.createGig(
    [
      "Build a Fullstack Web3 App", 
      "I will build a React frontend and Solidity smart contracts for your business.", 
      "Development", 
      parseEther("0.1") // Price in ETH
    ],
    { account: seller.account }
  );
  
  await publicClient.waitForTransactionReceipt({ hash: createGigTx });
  console.log("✅ Initial Gig created successfully!");

  console.log("\n🎉 All done! Copy the contract addresses above and paste them into your frontend config.");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });